{% set version = "6.5.1" %}
{% set python_min = "3.10" %}

package:
  name: kanapy
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/k/kanapy/kanapy-{{ version }}.tar.gz
  sha256: 52972842e450b6216382cb3ece7efcf796405dfaaeacb9c45a034b3280b4db89

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - scipy
    - seaborn
    - click
    - tqdm
    - jsonschema
    - networkx
    - orix >=0.13
    - scikit-image
    - requests

test:
  imports:
    - kanapy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://icams.github.io/Kanapy/builds/html/index.html
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'Python tool for microstructure analysis and generation of 3D microstructure models'
  description: |
    Kanapy is a python toolbox for the generation of 3D microstructure models based on 
    statistical analysis of experimental 2D microstructure maps. Grain orientations are generated 
    based on crystallographic textures.
  doc_url: https://icams.github.io/Kanapy/builds/html/index.html
  dev_url: https://github.com/ICAMS/Kanapy

extra:
  recipe-maintainers:
    - AHartmaier
    - jan-janssen
