{% set name = "kanapy" %}
{% set version = "6.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ICAMS/Kanapy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cabdc5ebcd3ba3df5d07b22a97daf60ed77cee437e51b3796e5954be20175bad

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]
  skip: true  # [py>=312]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - numpy
    - matplotlib-base
    - scipy
    - seaborn
    - click
    - tqdm
    - pytest-cov
    - pytest-mock
    - pytest
    - jsonschema
    - networkx
    - orix
    - scikit-image

test:
  imports:
    - kanapy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mrgprasad/kanapy
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: 'A python package for generating complex synthetic polycrystalline microstructures.'
  description: |
    Kanapy is a python package for generating complex synthetic 
    polycrystalline microstructures. The general implementation is done 
    in Python with the performance critical part for the geometry module 
    implemented in C++. 
  doc_url: https://github.com/mrgprasad/kanapy
  dev_url: https://github.com/mrgprasad/kanapy

extra:
  recipe-maintainers:
    - AHartmaier
    - jan-janssen
