schema_version: 1

context:
  version: "6.5.4"

package:
  name: kanapy
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/k/kanapy/kanapy-${{ version }}.tar.gz
  sha256: c7838452e6d6254554c24cc0a961ce217281b3079530ca7de6d2e7b43664cd39

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}
    - numpy <=2.2.6
    - matplotlib-base
    - scipy
    - seaborn
    - click
    - tqdm
    - jsonschema
    - networkx
    - orix >=0.13
    - scikit-image
    - requests

tests:
  - python:
      imports:
        - kanapy
      pip_check: true
      python_version:
        - ${{ python_min }}
        - "*"

about:
  license: AGPL-3.0-or-later
  license_file: LICENSE
  summary: Python tool for microstructure analysis and generation of 3D microstructure models
  description: |
    Kanapy is a python toolbox for the generation of 3D microstructure models based on
    statistical analysis of experimental 2D microstructure maps. Grain orientations are generated
    based on crystallographic textures.
  homepage: https://icams.github.io/Kanapy/builds/html/index.html
  repository: https://github.com/ICAMS/Kanapy
  documentation: https://icams.github.io/Kanapy/builds/html/index.html

extra:
  recipe-maintainers:
    - AHartmaier
    - jan-janssen
